### ISSUE TITLE
More Rust-y wrapping

### ISSUE THREAD

**Issue by netvl** [KevinKelley/nanovg-rs#2]
@KevinKelley, first, thank you for the library! It really is great!

I noticed, however, that the wrapping is pretty low-level. For example, there are public functions which expect raw pointers; also some structures exposed as-is, with libc-typed fields.

Here is the list of things I have found:
- [x] `NVGcolor` is exported without any wrapping, and global functions create its instances;
- [x] `NVGcontext` is not a proper opaque type; moreover, `Ctx` contains public pointer to it;
- [ ] `NVGpaint`, `NVGglyphPosition` and `NVGtextRow` are exported directly;
- [x] fonts and images handles are exposed directly as `i32`;
- [x] transformation matrices are represented by raw pointers;
- [ ] a lot of functions accept raw pointers, either for input or output (too many, won't list all of them).

These things need to be fixed to provide safe, libc types-free and raw pointer-less API.

If you don't mind, I'm willing to work at least on some of these items. It shouldn't be too hard, but some new abstractions will be needed. You can track my progress in [my fork](https://github.com/netvl/nanovg-rs).

**Comment by Lisoph** [comment]
So I guess this issue can be closed, right? If there are any missing functionalities in the current API, we should probably open a new issue for tracking them.

**Comment by KevinKelley** [comment]
Yup, I think so

**Comment by Lisoph** [comment]
I'll close it then.
