### ISSUE TITLE
Subpath usability

### ISSUE THREAD

**Issue by zxey** [KevinKelley/nanovg-rs#45]
While porting #44, I encountered few usability problems concerning drawing paths and their subpaths:
The first problem is when i only wanted to draw line, I needed to write:
```
frame.path(|path| {
    path.sub_path((move_x, move_y), |sub_path| {
        sub_path.line_to((to_x, to_y));
    });

    path.stroke(...);
}, Default::default());
```
This seems quite cumbersome, but the first thing I though would work is just to call move_to and line_to on the path itself.

The second, more concerning problem is regarding creating holes in paths.
For example, I want to draw rectangle and then cut a hole in that rectangle using another rectangle, like this: 
![cutout](https://user-images.githubusercontent.com/5235838/36565308-618a3e0e-1820-11e8-8761-fd909bef7376.png)
(the black rectangle is the first rectangle, the second one is rounded and cuts hole into the first one)
The way you would do it in c version of nanovg is as follows (parameteres excluded for clarity):
```
nvgBeginPath(...);
nvgRect(...); // first rect
nvgRoundedRect(...); // second rect to cutout from the first rect (with ofset x and y)
nvgPathWinding(NVG_HOLE);
nvgFillColor(black);
nvgFill(...);
```
The way you do it now in nanovg-rs:
```
frame.path(|path| {
    path.rect(...); // first rect
    path.sub_path((0.0, 0.0), |sub_path| {
        path.rounded_rect(...); // second rect to cutout from the first rect (with ofset x and y)
        sub_path.winding(Winding::Solidity(Solidity::Hole));
    });
    path.fill(...);
}, Default::default());
```
To figure this out, took me embarrasingly long time.
The coordinates when calling sub_path function (0.0, 0.0) are also not needed, which creates more confusion.
So i propose that we remove SubPath struct and move all code back to Path struct.
If it is desired we can keep the sub_path function which would just do move_to and call closure without parameter like this:
```
frame.path(|path| {
    path.rect(...); // first rect
    path.sub_path((0.0, 0.0), || {
        // these two lines can also be moved outside of this closure if wanted to
        path.rounded_rect(...); // second rect to cutout from the first rect (with ofset x and y)
        path.winding(Winding::Solidity(Solidity::Hole)); // <-- not using sub_path here, only path instance
    });
    path.fill(...);
}, Default::default());
```

There's the example I created for the screenshot: [Link](https://gist.github.com/zxey/a864240d43b0ee1427b5eb466042ae84)
You need to put it in examples folder and add this to the end of Cargo.toml:
```
[[example]]
name = "demo-cutout"
```

**Comment by Lisoph** [comment]
> So i propose that we remove SubPath struct and move all code back to Path struct.

Agreed, this seems way better. I'm going to fix this in a minute.
