### ISSUE TITLE
Are we using libc = "*" for a reason?

### ISSUE THREAD

**Issue by Lisoph** [KevinKelley/nanovg-rs#51]
If not, we should probably specify a version.

See [Cargo.toml](../blob/master/Cargo.toml#L24)

**Comment by KevinKelley** [comment]
I don't know that it matters, I take it to mean "any version", and that we don't care.  If there's a reason to specify, go for it...

**Comment by zxey** [comment]
I think we should specify version, so if there is any breakage in libc crate, we can address it whenever we want to update libc crate again. Latest version as of writing this is `0.2.40`, so we can put `libc = "0.2"` in Cargo.toml and be done with it.

**Comment by KevinKelley** [comment]
Sounds fine... for common crates we can probably assume that they'll maintain api, so it's counterproductive to pick out a particular revision.  We don't want to deliberately target old versions, unless there's a need... so yah: libc="0.2" sounds reasonable.
