### ISSUE TITLE
Provide Eq implementation for Alignment

### ISSUE THREAD

**Issue by mruegenberg** [KevinKelley/nanovg-rs#75]
Hello,
I founds this to be a small problem while digging though some old code of mine. It seems like this used to work, but doesn't anymore.

Sometimes, it might be useful to compare alignments for equality. A bonus would be the ability to compare the horizontal and vertical alignments separately as well.

**Comment by KevinKelley** [comment]
PR welcome...

**Comment by mruegenberg** [comment]
Sure, I'll try to send one sometime next week :)
