### ISSUE TITLE
WebGL support

### ISSUE THREAD

**Issue by SkylerLipthay** [KevinKelley/nanovg-rs#76]
Hi! It might be a long shot, but have you thought at all about what it would take to get this crate running within a WASM context, targeting WebGL? I know NanoVG itself has received [minor attention](https://github.com/memononen/nanovg/issues/398) on this question. I've been working a bit on recoding NanoVG in Rust with a particular focus on targeting WebGL, but I think this is silly given how much is already done here.

Personally I'm a bit lost on how emscripten re-targets GLES2 code to WebGL (see the linked issue), so I'm not sure yet what would be the best way to attack this problem... Just wanted to see if anyone has had any thoughts!

**Comment by KevinKelley** [comment]
Interesting... haven't thought about it, no, but sounds cool.  

A little googling finds [this rust/webgl example](https://github.com/likr/rust-webgl2-example) ...so I guess something like this is possible

**Comment by SkylerLipthay** [comment]
I think the biggest hurdle has to do with coercing NanoVG to interface with the WebGL API. WebGL is subset of GLES2, but there still has to be some sort of mapping layer between the WebGL and GLES2 APIs (because WebGL is built for JS; GL for C). Emscripten seems to provide [such a layer](https://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html#opengl-support-webgl-subset), but I'm not sure WebAssembly (itself an evolution of Emscripten) has such a thing yet.

Anyway my long-term goal is to be able to code performant web GUIs in Rust, and I think something like NanoVG could be the basis. I'll post here if I make any progress relevant to this project. Thanks!
