### ISSUE TITLE
`text_break_lines` gives different results based on most recend call to `text`

### ISSUE THREAD

**Issue by porky11** [KevinKelley/nanovg-rs#78]
This is unexpected behavior and should at least be documented, but preferably changed.
I assume, it just has been forgotten to add,  since almost all other functions take a font and some text options, which are passed to private function `text_prepare`. So just adding a font and text options as parameters here as well should solve this issue.

**Comment by KevinKelley** [comment]
Sounds reasonable, and yeah, that is definitely unexpected and not wanted, I'd say

**Comment by porky11** [comment]
Updating the examples also didn't help. I assume it's necessary to get rid of macro `f32_eq!`, which doesn't exist.
I'll probably try to upgrade this lib to most recent rust, and make the tests work again, when I have time.
